import{SELF}from'cloudflare:test';import{describe,expect,it}from'vitest';const AUTH={'x-api-key':'dev-api-key','content-type':'application/json'}
describe('agentes IA',()=>{it('lista o agente padrão e alterna atendimento global',async()=>{const list=await SELF.fetch('https://x.com/api/agents',{headers:AUTH});expect(list.status).toBe(200);expect(await list.json()).toEqual(expect.objectContaining({enabled:true,items:expect.arrayContaining([expect.objectContaining({id:'agent_commercial',name:'Agente Comercial',active:true,is_default:true,temperature:0.7,max_tokens:1024,debounce_ms:5000,rag_max_results:5,handoff_enabled:true})])}));const disabled=await SELF.fetch('https://x.com/api/agents/enabled',{method:'PUT',headers:AUTH,body:JSON.stringify({enabled:false})});expect(disabled.status).toBe(200);expect(await disabled.json()).toEqual({enabled:false})});it('cria e configura perfil de agente',async()=>{const created=await SELF.fetch('https://x.com/api/agents',{method:'POST',headers:AUTH,body:JSON.stringify({name:'Agente Suporte',description:'Resolve dúvidas',instructions:'Use somente a base e encaminhe quando faltar informação.',active:true,temperature:0.3,max_tokens:768,debounce_ms:3200,rag_similarity_threshold:0.65,rag_max_results:8,handoff_enabled:false,handoff_instructions:''})});expect(created.status).toBe(201);const{id}=await created.json()as{id:string};expect((await SELF.fetch(`https://x.com/api/agents/${id}`,{method:'PATCH',headers:AUTH,body:JSON.stringify({name:'Agente Suporte N1',description:'Resolve dúvidas simples',instructions:'Use somente a base e nunca invente fatos.',active:false,temperature:0.4,max_tokens:896,debounce_ms:4000,rag_similarity_threshold:0.7,rag_max_results:6,handoff_enabled:true,handoff_instructions:'Transfira somente quando necessário.'})})).status).toBe(200);const list=await(await SELF.fetch('https://x.com/api/agents',{headers:AUTH})).json()as{items:Array<{id:string;name:string;active:boolean}>};expect(list.items).toEqual(expect.arrayContaining([expect.objectContaining({id,name:'Agente Suporte N1',active:false,temperature:0.4,max_tokens:896,debounce_ms:4000,rag_similarity_threshold:0.7,rag_max_results:6,handoff_enabled:true})]))});it('permite simular um agente inativo sem expô-lo ao inbox',async()=>{const created=await SELF.fetch('https://x.com/api/agents',{method:'POST',headers:AUTH,body:JSON.stringify({name:'Agente em auditoria',description:'',instructions:'Use a base.',active:false,temperature:0.7,max_tokens:1024,debounce_ms:5000,rag_similarity_threshold:0.5,rag_max_results:5,handoff_enabled:true,handoff_instructions:'Encaminhe quando não houver resposta.'})});expect(created.status).toBe(201);const{id}=await created.json()as{id:string};const tested=await SELF.fetch(`https://x.com/api/agents/${id}/test`,{method:'POST',headers:AUTH,body:JSON.stringify({message:'qual é o código?'})});expect(tested.status).toBe(200);expect(await tested.json()).toEqual({text:'Este agente ainda não possui documentos vinculados. Vou encaminhar para uma pessoa.',grounded:false})})})

describe('simulador multi-turno de agente',()=>{it('aceita histórico sem exigir ativar o agente',async()=>{const created=await SELF.fetch('https://x.com/api/agents',{method:'POST',headers:AUTH,body:JSON.stringify({name:'Agente multi-turno',description:'',instructions:'Não repita perguntas já respondidas.',active:false,temperature:0.2,max_tokens:512,debounce_ms:0,rag_similarity_threshold:0.2,rag_max_results:5,handoff_enabled:true,handoff_instructions:'Encaminhe quando faltar fonte.'})});const{id}=await created.json()as{id:string};const response=await SELF.fetch(`https://x.com/api/agents/${id}/test`,{method:'POST',headers:AUTH,body:JSON.stringify({messages:[{role:'assistant',text:'Qual é o seu nome?'},{role:'user',text:'Meu nome é Ana.'}]})});expect(response.status).toBe(200);expect(await response.json()).toEqual({text:'Este agente ainda não possui documentos vinculados. Vou encaminhar para uma pessoa.',grounded:false})});it('rejeita payload ambíguo com message e messages',async()=>{const response=await SELF.fetch('https://x.com/api/agents/agent_commercial/test',{method:'POST',headers:AUTH,body:JSON.stringify({message:'Olá',messages:[{role:'user',text:'Olá'}]})});expect(response.status).toBe(400)});it('exige que o histórico termine com mensagem do cliente',async()=>{const response=await SELF.fetch('https://x.com/api/agents/agent_commercial/test',{method:'POST',headers:AUTH,body:JSON.stringify({messages:[{role:'user',text:'Preciso de ajuda.'},{role:'assistant',text:'Como posso ajudar?'}]})});expect(response.status).toBe(400);expect(await response.json()).toEqual({error:'a última mensagem da conversa precisa ser do cliente'})})})

describe('política canônica no simulador de agente', () => {
  it('usa os mesmos estados da automação sem depender da variação do modelo', async () => {
    const response = await SELF.fetch(
      'https://x.com/api/agents/agent_commercial/test',
      {
        method: 'POST',
        headers: AUTH,
        body: JSON.stringify({
          message: 'HTTP 200 quer dizer que a mensagem foi entregue e lida?',
        }),
      },
    )
    expect(response.status).toBe(200)
    expect(await response.json()).toEqual({
      text: expect.stringMatching(/sent.*delivered.*read.*failed/),
      grounded: true,
    })
  })
})
